# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6906489980ede6ff8db68c1ee40174fd14aa5e1171693a6f4c4c1d65d17fdc66fadac5caefed68dc6fa519b46765c4a9485627ab83517086a73241c6bd1b730

test:
  secret_key_base: f726a8050cd24d10eebaf860ceaf9e9307eae454b369758596bd6a7754bc371bf1471cd526d8c7a9c191b1c1a618ab9c15c48764f38a399d4769f654c3e9ad8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
